// Fallback-Typedeklarationen für Strudel (handgeschrieben, lax typisiert).
// Ersetzbar durch die offiziell generierte Datei aus PR #1542 (npm run jsdoc-to-dts).

declare class Pattern {
  // Pattern transforms
  fast(...args: any[]): Pattern;
  slow(...args: any[]): Pattern;
  hurry(...args: any[]): Pattern;
  density(...args: any[]): Pattern;
  early(...args: any[]): Pattern;
  late(...args: any[]): Pattern;
  compress(...args: any[]): Pattern;
  zoom(...args: any[]): Pattern;
  reset(...args: any[]): Pattern;
  segment(...args: any[]): Pattern;
  smooth(...args: any[]): Pattern;
  quantise(...args: any[]): Pattern;
  quantize(...args: any[]): Pattern;
  clip(...args: any[]): Pattern;
  loop(...args: any[]): Pattern;
  loopAt(...args: any[]): Pattern;
  ply(...args: any[]): Pattern;
  braces(...args: any[]): Pattern;
  slowcat(...args: any[]): Pattern;
  fastcat(...args: any[]): Pattern;
  cat(...args: any[]): Pattern;
  sequence(...args: any[]): Pattern;
  seq(...args: any[]): Pattern;
  stack(...args: any[]): Pattern;
  weave(...args: any[]): Pattern;
  spread(...args: any[]): Pattern;
  spreadf(...args: any[]): Pattern;
  timeCat(...args: any[]): Pattern;
  timecat(...args: any[]): Pattern;
  repeat(...args: any[]): Pattern;
  end(...args: any[]): Pattern;
  begin(...args: any[]): Pattern;

  // Ordering / selection
  rev(...args: any[]): Pattern;
  palindrome(...args: any[]): Pattern;
  shuffle(...args: any[]): Pattern;
  scramble(...args: any[]): Pattern;
  degenerate(...args: any[]): Pattern;
  rot(...args: any[]): Pattern;
  rotL(...args: any[]): Pattern;
  rotR(...args: any[]): Pattern;
  invert(...args: any[]): Pattern;
  every(...args: any[]): Pattern;
  when(...args: any[]): Pattern;
  sometimes(...args: any[]): Pattern;
  often(...args: any[]): Pattern;
  rarely(...args: any[]): Pattern;
  almostNever(...args: any[]): Pattern;
  almostAlways(...args: any[]): Pattern;
  never(...args: any[]): Pattern;
  always(...args: any[]): Pattern;
  struct(...args: any[]): Pattern;
  mask(...args: any[]): Pattern;
  focus(...args: any[]): Pattern;
  focusMin(...args: any[]): Pattern;
  focusMax(...args: any[]): Pattern;
  jux(...args: any[]): Pattern;
  off(...args: any[]): Pattern;
  superimpose(...args: any[]): Pattern;
  echo(...args: any[]): Pattern;
  stut(...args: any[]): Pattern;
  brak(...args: any[]): Pattern;
  brake(...args: any[]): Pattern;
  swing(...args: any[]): Pattern;
  gap(...args: any[]): Pattern;
  stair(...args: any[]): Pattern;
  distrib(...args: any[]): Pattern;
  defer(...args: any[]): Pattern;
  inside(...args: any[]): Pattern;
  outside(...args: any[]): Pattern;

  // Rhythm / structure
  trig(...args: any[]): Pattern;
  trigg(...args: any[]): Pattern;
  t(...args: any[]): Pattern;
  bin(...args: any[]): Pattern;
  euclid(...args: any[]): Pattern;
  euclidRot(...args: any[]): Pattern;
  euclidSteps(...args: any[]): Pattern;
  binary(...args: any[]): Pattern;
  splice(...args: any[]): Pattern;
  fit(...args: any[]): Pattern;
  chop(...args: any[]): Pattern;
  striate(...args: any[]): Pattern;
  striateBy(...args: any[]): Pattern;
  slice(...args: any[]): Pattern;
  soft(...args: any[]): Pattern;

  // Value manipulation
  fmap(...args: any[]): Pattern;
  map(...args: any[]): Pattern;
  withValue(...args: any[]): Pattern;
  withHap(...args: any[]): Pattern;
  withEvent(...args: any[]): Pattern;
  withEvents(...args: any[]): Pattern;
  withQuery(...args: any[]): Pattern;
  appl(...args: any[]): Pattern;
  apply(...args: any[]): Pattern;
  add(...args: any[]): Pattern;
  sub(...args: any[]): Pattern;
  mul(...args: any[]): Pattern;
  div(...args: any[]): Pattern;
  mod(...args: any[]): Pattern;
  range(...args: any[]): Pattern;
  rangex(...args: any[]): Pattern;
  toBipolar(...args: any[]): Pattern;
  fromBipolar(...args: any[]): Pattern;

  // Control parameters
  s(...args: any[]): Pattern;
  sound(...args: any[]): Pattern;
  n(...args: any[]): Pattern;
  note(...args: any[]): Pattern;
  freq(...args: any[]): Pattern;
  pan(...args: any[]): Pattern;
  gain(...args: any[]): Pattern;
  velocity(...args: any[]): Pattern;
  attack(...args: any[]): Pattern;
  decay(...args: any[]): Pattern;
  dec(...args: any[]): Pattern;
  sustain(...args: any[]): Pattern;
  release(...args: any[]): Pattern;
  adsr(...args: any[]): Pattern;
  cutoff(...args: any[]): Pattern;
  lpf(...args: any[]): Pattern;
  hpf(...args: any[]): Pattern;
  bandf(...args: any[]): Pattern;
  bandq(...args: any[]): Pattern;
  resonance(...args: any[]): Pattern;
  hresonance(...args: any[]): Pattern;
  lpq(...args: any[]): Pattern;
  hpq(...args: any[]): Pattern;
  bpq(...args: any[]): Pattern;
  vowel(...args: any[]): Pattern;
  shape(...args: any[]): Pattern;
  crush(...args: any[]): Pattern;
  coarse(...args: any[]): Pattern;
  distort(...args: any[]): Pattern;
  preamp(...args: any[]): Pattern;
  accelerate(...args: any[]): Pattern;
  detune(...args: any[]): Pattern;
  fm(...args: any[]): Pattern;
  fmh(...args: any[]): Pattern;
  am(...args: any[]): Pattern;
  amh(...args: any[]): Pattern;
  tremolo(...args: any[]): Pattern;
  vibrato(...args: any[]): Pattern;
  speed(...args: any[]): Pattern;
  legato(...args: any[]): Pattern;
  porta(...args: any[]): Pattern;
  arp(...args: any[]): Pattern;
  arpWith(...args: any[]): Pattern;
  delay(...args: any[]): Pattern;
  delaytime(...args: any[]): Pattern;
  delayfeedback(...args: any[]): Pattern;
  room(...args: any[]): Pattern;
  roomsize(...args: any[]): Pattern;
  size(...args: any[]): Pattern;
  duck(...args: any[]): Pattern;
  duckattack(...args: any[]): Pattern;
  lpenv(...args: any[]): Pattern;
  lpattack(...args: any[]): Pattern;
  lpdecay(...args: any[]): Pattern;
  lpsustain(...args: any[]): Pattern;
  lprelease(...args: any[]): Pattern;
  hpenv(...args: any[]): Pattern;
  hpattack(...args: any[]): Pattern;
  hpdecay(...args: any[]): Pattern;
  hpsustain(...args: any[]): Pattern;
  hprelease(...args: any[]): Pattern;
  bpenv(...args: any[]): Pattern;
  bpattack(...args: any[]): Pattern;
  bpdecay(...args: any[]): Pattern;
  bpsustain(...args: any[]): Pattern;
  bprelease(...args: any[]): Pattern;
  out(...args: any[]): Pattern;
  orbit(...args: any[]): Pattern;
  bank(...args: any[]): Pattern;
  scale(...args: any[]): Pattern;
  trans(...args: any[]): Pattern;
  mtrans(...args: any[]): Pattern;
  chroma(...args: any[]): Pattern;
  semitones(...args: any[]): Pattern;
  st(...args: any[]): Pattern;
  g(...args: any[]): Pattern;
  c(...args: any[]): Pattern;
  o(...args: any[]): Pattern;
  postgain(...args: any[]): Pattern;
  softclip(...args: any[]): Pattern;
  voicing(...args: any[]): Pattern;
  as(...args: any[]): Pattern;

  // Custom / visual helpers
  rib(...args: any[]): Pattern;
  seg(...args: any[]): Pattern;
  rfade(...args: any[]): Pattern;
  _pianoroll(...args: any[]): Pattern;
  _spectrum(...args: any[]): Pattern;
  _punchcard(...args: any[]): Pattern;
  _graph(...args: any[]): Pattern;
  _canvas(...args: any[]): Pattern;

  set: any;
}

declare function setCps(...args: any[]): void;
declare function getCps(): number;
declare function setTempo(...args: any[]): void;
declare function now(): number;
declare function currentTime(): number;
declare function cps(...args: any[]): any;
declare function bpm(...args: any[]): any;

declare const silence: Pattern;

declare function s(...args: any[]): Pattern;
declare function sound(...args: any[]): Pattern;
declare function n(...args: any[]): Pattern;
declare function note(...args: any[]): Pattern;
declare function freq(...args: any[]): Pattern;
declare function pan(...args: any[]): Pattern;
declare function gain(...args: any[]): Pattern;
declare function velocity(...args: any[]): Pattern;
declare function attack(...args: any[]): Pattern;
declare function decay(...args: any[]): Pattern;
declare function sustain(...args: any[]): Pattern;
declare function release(...args: any[]): Pattern;
declare function cutoff(...args: any[]): Pattern;
declare function lpf(...args: any[]): Pattern;
declare function hpf(...args: any[]): Pattern;
declare function bandf(...args: any[]): Pattern;
declare function bandq(...args: any[]): Pattern;
declare function resonance(...args: any[]): Pattern;
declare function hresonance(...args: any[]): Pattern;
declare function vowel(...args: any[]): Pattern;
declare function shape(...args: any[]): Pattern;
declare function crush(...args: any[]): Pattern;
declare function coarse(...args: any[]): Pattern;
declare function distort(...args: any[]): Pattern;
declare function accelerate(...args: any[]): Pattern;
declare function detune(...args: any[]): Pattern;
declare function fm(...args: any[]): Pattern;
declare function fmh(...args: any[]): Pattern;
declare function am(...args: any[]): Pattern;
declare function amh(...args: any[]): Pattern;
declare function tremolo(...args: any[]): Pattern;
declare function vibrato(...args: any[]): Pattern;
declare function speed(...args: any[]): Pattern;
declare function legato(...args: any[]): Pattern;
declare function porta(...args: any[]): Pattern;
declare function arp(...args: any[]): Pattern;
declare function arpWith(...args: any[]): Pattern;
declare function delay(...args: any[]): Pattern;
declare function delaytime(...args: any[]): Pattern;
declare function delayfeedback(...args: any[]): Pattern;
declare function room(...args: any[]): Pattern;
declare function roomsize(...args: any[]): Pattern;
declare function duck(...args: any[]): Pattern;
declare function duckattack(...args: any[]): Pattern;
declare function lpenv(...args: any[]): Pattern;
declare function bpenv(...args: any[]): Pattern;
declare function hpenv(...args: any[]): Pattern;
declare function orbit(...args: any[]): Pattern;
declare function bank(...args: any[]): Pattern;
declare function scale(...args: any[]): Pattern;
declare function trans(...args: any[]): Pattern;
declare function voicing(...args: any[]): Pattern;
declare function as(...args: any[]): Pattern;
declare function adsr(...args: any[]): Pattern;

declare function stack(...args: any[]): Pattern;
declare function seq(...args: any[]): Pattern;
declare function sequence(...args: any[]): Pattern;
declare function cat(...args: any[]): Pattern;
declare function slowcat(...args: any[]): Pattern;
declare function fastcat(...args: any[]): Pattern;
declare function timeCat(...args: any[]): Pattern;
declare function timecat(...args: any[]): Pattern;
declare function fast(...args: any[]): Pattern;
declare function slow(...args: any[]): Pattern;
declare function hurry(...args: any[]): Pattern;
declare function early(...args: any[]): Pattern;
declare function late(...args: any[]): Pattern;
declare function density(...args: any[]): Pattern;
declare function rev(...args: any[]): Pattern;
declare function palindrome(...args: any[]): Pattern;
declare function shuffle(...args: any[]): Pattern;
declare function scramble(...args: any[]): Pattern;
declare function degenerate(...args: any[]): Pattern;
declare function every(...args: any[]): Pattern;
declare function when(...args: any[]): Pattern;
declare function sometimes(...args: any[]): Pattern;
declare function often(...args: any[]): Pattern;
declare function rarely(...args: any[]): Pattern;
declare function almostNever(...args: any[]): Pattern;
declare function almostAlways(...args: any[]): Pattern;
declare function never(...args: any[]): Pattern;
declare function always(...args: any[]): Pattern;
declare function add(...args: any[]): Pattern;
declare function sub(...args: any[]): Pattern;
declare function mul(...args: any[]): Pattern;
declare function div(...args: any[]): Pattern;
declare function mod(...args: any[]): Pattern;
declare function off(...args: any[]): Pattern;
declare function jux(...args: any[]): Pattern;
declare function superimpose(...args: any[]): Pattern;
declare function echo(...args: any[]): Pattern;
declare function stut(...args: any[]): Pattern;
declare function brak(...args: any[]): Pattern;
declare function brake(...args: any[]): Pattern;
declare function swing(...args: any[]): Pattern;
declare function inside(...args: any[]): Pattern;
declare function outside(...args: any[]): Pattern;
declare function ply(...args: any[]): Pattern;
declare function euclid(...args: any[]): Pattern;
declare function euclidRot(...args: any[]): Pattern;
declare function euclidSteps(...args: any[]): Pattern;
declare function binary(...args: any[]): Pattern;
declare function trig(...args: any[]): Pattern;
declare function trigg(...args: any[]): Pattern;
declare function t(...args: any[]): Pattern;
declare function bin(...args: any[]): Pattern;
declare function struct(...args: any[]): Pattern;
declare function mask(...args: any[]): Pattern;
declare function splice(...args: any[]): Pattern;
declare function fit(...args: any[]): Pattern;
declare function chop(...args: any[]): Pattern;
declare function striate(...args: any[]): Pattern;
declare function segment(...args: any[]): Pattern;
declare function smooth(...args: any[]): Pattern;
declare function quantise(...args: any[]): Pattern;
declare function quantize(...args: any[]): Pattern;
declare function compress(...args: any[]): Pattern;
declare function zoom(...args: any[]): Pattern;
declare function rot(...args: any[]): Pattern;
declare function rotL(...args: any[]): Pattern;
declare function rotR(...args: any[]): Pattern;
declare function weave(...args: any[]): Pattern;
declare function spread(...args: any[]): Pattern;
declare function spreadf(...args: any[]): Pattern;
declare function zip(...args: any[]): Pattern;
declare function mini(...args: any[]): Pattern;

declare const rand: Pattern;
declare const rand2: Pattern;
declare const saw: Pattern;
declare const isaw: Pattern;
declare const sine: Pattern;
declare const cosine: Pattern;
declare const square: Pattern;
declare const tri: Pattern;
declare const perlin: Pattern;
declare const time: Pattern;
declare function signal(...args: any[]): Pattern;

declare function chord(...args: any[]): Pattern;
declare function chordName(...args: any[]): any;
declare function chordToMidi(...args: any[]): any;
declare function scaleNotes(...args: any[]): any;
declare function noteToMidi(...args: any[]): any;
declare function midiToNote(...args: any[]): any;
declare function freqToMidi(...args: any[]): any;
declare function midiToFreq(...args: any[]): any;

declare function samples(...args: any[]): void;
declare function sample(...args: any[]): Pattern;
declare function registerSynthSounds(...args: any[]): void;
declare function initAudioOnFirstClick(...args: any[]): void;
declare function webaudioOutput(...args: any[]): any;
declare function getAudioContext(...args: any[]): any;
declare function superdough(...args: any[]): void;
declare function repl(...args: any[]): any;

declare function midikeys(...args: any[]): (...args: any[]) => Pattern;
declare function midichan(...args: any[]): Pattern;
declare function midi(...args: any[]): any;

declare function slider(...args: any[]): any;
declare function checkbox(...args: any[]): any;
declare function dropdown(...args: any[]): any;
declare function toggle(...args: any[]): any;

declare function all(...args: any[]): any;
declare function drum(...args: any[]): Pattern;
declare function evalScope(...args: any[]): any;

interface Window {
  [key: string]: any;
}
